version: '3.7'

services:
    cpp_env:
        build:
            context: .
            target: builder
        command: /bin/sh -c "while sleep 1000; do :; done"
        environment:
          - BUILDPATH=../build
        volumes:
            - .:/OO_CPP